import jidouteki
from jidouteki import Config, Chapter
from jidouteki.utils import get
import json
import blackboxprotobuf
import random
import hashlib
import re

SECRET_KEY = "4Kin9vGg"
APP_PARAMS = {
    "os": "android",
    "os_ver": "34",
    "app_ver": 169
}

def md5(string: str):
    return hashlib.md5(string.encode()).digest().hex()

@jidouteki.register
class Mangaplus(Config):
    def init(self):
        self.__secret = None
        self.session.headers.update({ "User-Agent": "okhttp/4.12.0" })
    
    @jidouteki.meta
    def _meta(self):
        return jidouteki.Metadata(
            key = "mangaplus",
            display_name = "Manga Plus",
            base = "https://jumpg-api.tokyo-cdn.com/"
        )
    
    @jidouteki.match
    def _match(self, url):
        SERIES_MATCH = r"https://mangaplus.shueisha.co.jp/titles/(?P<series>\d+)"
        if (m := re.match(SERIES_MATCH, url)): return m.groupdict()

        CHAPTER_MATCH = r"https://mangaplus.shueisha.co.jp/viewer/(?P<chapter>\d+)"
        if (m := re.match(CHAPTER_MATCH, url)):
            match = m.groupdict()
            
            d = self._fetch_viewer(match.get("chapter"))
            
            return {
                **match,
                "series": str(get(d, "1.10.9"))
            }
    
    # Randomly generate a valid (token, key) pair
    def _gen_register_params(self):
        random_id = random.randbytes(8).hex()
        token = md5(random_id)
        security_key = md5(token + SECRET_KEY)
        return (token, security_key)
    
    # Register new device given a token and a key
    def _get_secret(self, token, key):
        result = self.fetch("/api/register", 
                            method="PUT",
                            params = { 
                                    "device_token": token, 
                                    "security_key": key, 
                                    **APP_PARAMS
                                    }
                            )
        if (result.data):
            message, _ = blackboxprotobuf.protobuf_to_json(result.data)
            message = json.loads(message)
            secret = get(message, "1.2.1")
            return secret
    
    def _fetch_title_details(self, series):
        result = self.fetch("/api/title_detailV3", params = {
            "title_id": series,
            **APP_PARAMS,
            "secret": self._secret,
        })
        
        message, _ = blackboxprotobuf.protobuf_to_json(result.data)
        message = json.loads(message)
        return message


    # Secure requests require a 'secret' parameter
    # The secret is generated by calling /register with a device_token and a security_key
    @property
    def _secret(self) -> str:
        if not self.__secret:
            self.__secret = self._get_secret(*self._gen_register_params())
        return self.__secret

    @jidouteki.series.chapters
    def _chapters(self, series: str):
        details = self._fetch_title_details(series)
        
        chapter_groups = get(details, "1.8.28")
        chapter_data = [] 
        for g in chapter_groups:
            for key, value in  g.items():
                if key != "1":
                    chapter_data.extend(value)
        
        chapters  = []
        for d in chapter_data:
            # series = d["1"]
            chapter_param = str(d["2"]) # 1009921
            chapter_value  = d["3"] # "#001"
            title = d["4"] # "Chapter 1: That's How Love Starts, Ya Know!"
            # thumbnail = d["5"]
            # release_timestamp = d["6"]
            # free_expire_timestamp =  d["7"]
            # _unknown = d["13"] # 837858
            # comments_count = d["14"]
            
            # "#001" -> 1, "One-shot" -> "One-shot"
            chapter_value = re.sub(r"(?:#0*(\d+)|(.+))", r"\1\2", chapter_value)

            chapters.append(Chapter(
                params = { "chapter": chapter_param },
                chapter = chapter_value,
                title = title,
                language = "en",
            ))

        return chapters

    @jidouteki.series.title
    def _title(self, series: str):
        d = self._fetch_title_details(series)
        return get(d, "1.8.1.2")
    
    @jidouteki.series.cover
    def _cover(self, series: str):
        d = self._fetch_title_details(series)
        return get(d, "1.8.1.4")
    
    def _fetch_viewer(self, chapter):
        result = self.fetch("/api/manga_viewer", params = {        
            "chapter_id": chapter,
            "split": "yes",
            "img_quality": "super_high",
            "ticket_reading": "no",
            "free_reading": "no",
            "subscription_reading": "yes",
            "viewer_mode": "horizontal",
            "clang": "eng",
            **APP_PARAMS,
            "secret": self._secret
        })

        message, _ = blackboxprotobuf.protobuf_to_json(result.data)
        message = json.loads(message)
        return message
        
    @jidouteki.images
    def _images(self, chapter: str):
        images  = []
        d = self._fetch_viewer(chapter)        
        for stuff in get(d, "1.10.1"):
            if "1" in stuff.keys():
                images.append(get(stuff, "1.1"))
        return images